theme: jekyll-theme-minimal
title: GTE PM Framework
description: Best practice process for project management at GTE Group
author: GTE
logo: "https://gtegroup.com.au/wp-content/uploads/2021/01/GTE-Logo-REV.svg"
show_downloads: "false"